### ISSUE TITLE
Host the addon outside of CurseForge

### ISSUE THREAD

**Issue by JVemmer** [fstenstrom/world-boss-timers#77]
As CurseForge is locking out everyone except Overwolf's own addon manager (source: [https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912](https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912)), please host this addon elsewhere than CurseForge (at least co-host it elsewhere). Options include:

- Hosting a .zip file of the addon here in the GitHub repository (this allows WowUp to pull it down)
- Hosting it on WowUpHub website
- Hosting it on wago.io (allows monetization to continue, if that is a concern)
- Hosting it on TukUI
- Hosting it on WowInterface

I am personally using WowUp to update addons, and while I very much respect that some addon creators want their work monetized, and believe that they should have the option, I do not support the Overwolf lock-out simply because they want everyone to use their app. If monetization is a priority, I suggest using wago.io as addon hosting, as it allows for monetization of addons, also while using WowUp; which shows they're willing to find solutions, rather than the Overwolf approach of refusing to cooperate.
I don't mind anyone hosting their addons on CurseForge, but please, please, please host it outside of CurseForge as well, for those of us who would like to cut ties with CurseForge, but still use your amazing addon :heart:

**Comment by fstenstrom** [comment]
I'm using WowUp myself so of course I'll fix this somehow.

I've made a source release, is this enough?
https://github.com/fstenstrom/world-boss-timers/releases/tag/v1.9.3

I looked for WowUpHub site but didn't find how to upload anything. Do you know of any guide?

**Comment by layday** [comment]
Hi @fstenstrom. You need to attach the add-on zip file to the release at a minimum and, ideally, `release.json` metadata.  The easiest way to accomplish both tasks is by using the [BigWigs packager](https://github.com/BigWigsMods/packager). You might find my [add-on template](https://github.com/layday/wow-addon-template) helpful for setting it up.

**Comment by JVemmer** [comment]
I think @layday covered most of it, in terms of making the addon installable via the URL, and ease of use. If you want it to show up in WowUp while searching (with Curse provider disabled), you have to ask the maintainers to include this repo in their searching. WowUp just published an FAQ on their Discord today (https://discord.gg/rk4F5aD), to help addon developers cope with the current chaos. And thank you for being amazing :heart:

**Comment by fstenstrom** [comment]
Thanks for directions. This was fixed in e5742ad2c15fb74e78441b4394dcc62b8a77b24a such that pushed tags now creates packaged source releases. v1.9.4 is now available as such.

I messaged WowUp mods on discord on Friday, but addon is still listed as under provider "Curse" instead of WowUpHub/GitHub. I guess there is some delay, so closing for now (and I'll keep an eye on it).

**Comment by JVemmer** [comment]
> I messaged WowUp mods on discord on Friday, but addon is still listed as under provider "Curse" instead of WowUpHub/GitHub. I guess there is some delay, so closing for now (and I'll keep an eye on it).

Thank you so much for this! :heart: WowUp devs just poked me on their Discord, and said that it should be up and running now. Since the addon can still be found on Curse, it may show "Curse" as the provider for people who still have that provider enabled, until Overwolf shuts down the connection. I just checked, and the WowUpHub provider is available, and it can also be installed directly via the GitHub link - so everything is working 😄 I did notice that the version on Curse was 1.9.4 vs. 1.9.3 here, though the Curse changelog seemed to point to this commit.
